import { Lead } from "./types";
import { scoreLead } from "./score";
import { validateLead } from "./validate";

type SeedInput = Omit<
  Lead,
  "score" | "scoreBreakdown" | "validation" | "status" | "duplicateOf" | "notes"
> & { status?: Lead["status"]; notes?: string };

function build(raw: SeedInput): Lead {
  const validation = validateLead({
    email: raw.email,
    domain: raw.domain,
    contactName: raw.contactName,
    title: raw.title,
    company: raw.company,
  });
  const partial = {
    ...raw,
    status: raw.status ?? ("new" as const),
    validation,
    duplicateOf: null,
    notes: raw.notes ?? "",
  };
  const { score, scoreBreakdown } = scoreLead(partial);
  return { ...partial, score, scoreBreakdown };
}

const scrapedAt = "2026-09-20T14:22:00.000Z";

export function createSeedLeads(): Lead[] {
  const rows: SeedInput[] = [
    {
      id: "ld_01",
      company: "Northwind Analytics",
      domain: "northwindanalytics.com",
      contactName: "Priya Shah",
      title: "VP of Sales",
      email: "priya.shah@northwindanalytics.com",
      phone: "+1-415-555-0142",
      linkedin: "https://linkedin.com/in/priyashah",
      industry: "SaaS",
      employeeCount: 85,
      revenueEstimate: 12_000_000,
      location: "San Francisco, CA",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_02",
      company: "Northwind Analytics",
      domain: "northwindanalytics.com",
      contactName: "Priya Shah",
      title: "VP Sales",
      email: "priya.shah@northwindanalytics.com",
      phone: null,
      linkedin: "https://linkedin.com/in/priyashah",
      industry: "Software",
      employeeCount: 90,
      revenueEstimate: 11_500_000,
      location: "SF Bay Area",
      source: "scrape:apollo-export",
      scrapedAt: "2026-09-21T09:10:00.000Z",
    },
    {
      id: "ld_03",
      company: "Harbor Health",
      domain: "harborhealth.io",
      contactName: "Marcus Lee",
      title: "Founder & CEO",
      email: "marcus@harborhealth.io",
      phone: "+1-617-555-0199",
      linkedin: "https://linkedin.com/in/marcuslee",
      industry: "Healthcare",
      employeeCount: 42,
      revenueEstimate: 6_800_000,
      location: "Boston, MA",
      source: "scrape:website",
      scrapedAt,
    },
    {
      id: "ld_04",
      company: "PixelCart",
      domain: "pixelcart.co",
      contactName: "Amy Chen",
      title: "Marketing Coordinator",
      email: "amy@pixelcart.co",
      phone: null,
      linkedin: null,
      industry: "E-commerce",
      employeeCount: 18,
      revenueEstimate: 900_000,
      location: "Austin, TX",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_05",
      company: "Ledgerly",
      domain: "ledgerly.com",
      contactName: "James Okonkwo",
      title: "CTO",
      email: "james@ledgerly.com",
      phone: "+1-212-555-0177",
      linkedin: "https://linkedin.com/in/jamesok",
      industry: "Fintech",
      employeeCount: 120,
      revenueEstimate: 22_000_000,
      location: "New York, NY",
      source: "scrape:crunchbase",
      scrapedAt,
    },
    {
      id: "ld_06",
      company: "Ledgerly Inc",
      domain: "ledgerly.com",
      contactName: "J. Okonkwo",
      title: "Chief Technology Officer",
      email: "james@ledgerly.com",
      phone: "+1-212-555-0177",
      linkedin: null,
      industry: "Fintech",
      employeeCount: 115,
      revenueEstimate: 20_000_000,
      location: "NYC",
      source: "scrape:linkedin",
      scrapedAt: "2026-09-19T11:00:00.000Z",
    },
    {
      id: "ld_07",
      company: "BrightHire",
      domain: "brighthire.app",
      contactName: "Sofia Alvarez",
      title: "Head of Growth",
      email: "sofia@brighthire.app",
      phone: null,
      linkedin: "https://linkedin.com/in/sofiaa",
      industry: "HR Tech",
      employeeCount: 55,
      revenueEstimate: 4_200_000,
      location: "Denver, CO",
      source: "scrape:website",
      scrapedAt,
    },
    {
      id: "ld_08",
      company: "QuickForm Labs",
      domain: "quickformlabs.com",
      contactName: "Tom Bradley",
      title: "Intern",
      email: "tombradley99@gmail.com",
      phone: null,
      linkedin: null,
      industry: "Software",
      employeeCount: 8,
      revenueEstimate: 120_000,
      location: "Remote",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_09",
      company: "ShieldOps",
      domain: "shieldops.security",
      contactName: "Nina Park",
      title: "Director of Partnerships",
      email: "nina.park@shieldops.security",
      phone: "+1-206-555-0133",
      linkedin: "https://linkedin.com/in/ninapark",
      industry: "Cybersecurity",
      employeeCount: 210,
      revenueEstimate: 38_000_000,
      location: "Seattle, WA",
      source: "scrape:apollo-export",
      scrapedAt,
    },
    {
      id: "ld_10",
      company: "CafeLocal",
      domain: "cafelocal.biz",
      contactName: "Rita Gomez",
      title: "Owner",
      email: "rita@mailinator.com",
      phone: "+1-503-555-0101",
      linkedin: null,
      industry: "Food & Beverage",
      employeeCount: 6,
      revenueEstimate: 350_000,
      location: "Portland, OR",
      source: "scrape:website",
      scrapedAt,
    },
    {
      id: "ld_11",
      company: "Orbit CRM",
      domain: "orbitcrm.io",
      contactName: "Daniel Kim",
      title: "Co-Founder",
      email: "dan@orbitcrm.io",
      phone: "+1-650-555-0188",
      linkedin: "https://linkedin.com/in/dankim",
      industry: "SaaS",
      employeeCount: 34,
      revenueEstimate: 5_500_000,
      location: "Palo Alto, CA",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_12",
      company: "Orbit CRM",
      domain: "orbitcrm.io",
      contactName: "Daniel Kim",
      title: "Co Founder",
      email: "dan@orbitcrm.io",
      phone: null,
      linkedin: "https://linkedin.com/in/dankim",
      industry: "Software",
      employeeCount: 30,
      revenueEstimate: null,
      location: "California",
      source: "csv-upload",
      scrapedAt: "2026-09-22T08:00:00.000Z",
    },
    {
      id: "ld_13",
      company: "MedStack",
      domain: "medstack.health",
      contactName: "Elena Rossi",
      title: "Product Manager",
      email: "elena@medstack.health",
      phone: null,
      linkedin: "https://linkedin.com/in/elenarossi",
      industry: "Healthcare",
      employeeCount: 75,
      revenueEstimate: 9_000_000,
      location: "Chicago, IL",
      source: "scrape:website",
      scrapedAt,
    },
    {
      id: "ld_14",
      company: "AdSpark Media",
      domain: "adspark.media",
      contactName: "Chris Nolan",
      title: "Account Executive",
      email: "not-an-email",
      phone: null,
      linkedin: null,
      industry: "Marketing",
      employeeCount: 40,
      revenueEstimate: 3_100_000,
      location: "Los Angeles, CA",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_15",
      company: "PayNest",
      domain: "paynest.co",
      contactName: "Aisha Rahman",
      title: "CEO",
      email: "aisha@paynest.co",
      phone: "+1-312-555-0164",
      linkedin: "https://linkedin.com/in/aisharahman",
      industry: "Fintech",
      employeeCount: 68,
      revenueEstimate: 14_000_000,
      location: "Chicago, IL",
      source: "scrape:crunchbase",
      scrapedAt,
    },
    {
      id: "ld_16",
      company: "CloudNest Solutions",
      domain: "cloudnest.io",
      contactName: "Ben Torres",
      title: "Sales Manager",
      email: "ben.torres@cloudnest.io",
      phone: "+1-480-555-0120",
      linkedin: null,
      industry: "SaaS",
      employeeCount: 95,
      revenueEstimate: 8_400_000,
      location: "Phoenix, AZ",
      source: "scrape:apollo-export",
      scrapedAt,
    },
    {
      id: "ld_17",
      company: "GreenGrid Energy",
      domain: "greengrid.energy",
      contactName: "Hannah Brooks",
      title: "Business Development Rep",
      email: "hannah@greengrid.energy",
      phone: null,
      linkedin: "https://linkedin.com/in/hannahbrooks",
      industry: "Clean Energy",
      employeeCount: 140,
      revenueEstimate: 28_000_000,
      location: "Boulder, CO",
      source: "scrape:linkedin",
      scrapedAt,
    },
    {
      id: "ld_18",
      company: "Formly",
      domain: "getformly.com",
      contactName: "Kevin Wu",
      title: "Founder",
      email: "kevin@getformly.com",
      phone: "+1-646-555-0190",
      linkedin: "https://linkedin.com/in/kevinwu",
      industry: "SaaS",
      employeeCount: 22,
      revenueEstimate: 2_100_000,
      location: "Brooklyn, NY",
      source: "scrape:website",
      scrapedAt,
    },
    {
      id: "ld_19",
      company: "Formly",
      domain: "getformly.com",
      contactName: "Kevin Wu",
      title: "Founder / CEO",
      email: "kevin@getformly.com",
      phone: "+1-646-555-0190",
      linkedin: "https://linkedin.com/in/kevinwu",
      industry: "Software",
      employeeCount: 25,
      revenueEstimate: 2_400_000,
      location: "New York",
      source: "csv-upload",
      scrapedAt: "2026-09-18T16:40:00.000Z",
    },
    {
      id: "ld_20",
      company: "Atlas Legal Tech",
      domain: "atlaslegal.tech",
      contactName: "Megan Foster",
      title: "COO",
      email: "megan@atlaslegal.tech",
      phone: "+1-215-555-0144",
      linkedin: "https://linkedin.com/in/megfoster",
      industry: "Legal Tech",
      employeeCount: 60,
      revenueEstimate: 7_200_000,
      location: "Philadelphia, PA",
      source: "scrape:crunchbase",
      scrapedAt,
    },
  ];

  return rows.map(build);
}
